### PR TITLE
fix: add undefined formatString fallback

### LINKED ISSUE #3: `formatString` fails when the key is not found
Hiya,

I am loading all my strings from a remote server (They are shared between several applications).

Some parts of the application are processed before the strings are fully loaded, and unfortunately I cannot stop that (for now).

When this happens, the `formatString` method falls over as it cannot do a `split()` on an `undefined` value. Submitting a PR for this very soon.

### PR DESCRIPTION
**Pull request by hvolschenk**
Add a fallback (empty string) value when the specified key is not found when calling `formatString()`.

closes #3

### CODE REVIEW

**Comment by hvolschenk** [comment]
All the empty space removals are done by my editor (I didn't realise until now). If you're opposed to that I will make a plan and change it.

Could I also suggest you look at this article to make your release process a bit more painless/automatic: https://medium.com/@righteous.trespasser/the-free-js-ci-checklist-5ea09dd0cab

**Comment by stefalda** [comment]
Thanks @hvolschenk

**Comment by hvolschenk** [comment]
Excellent. Should I create a PR to bump this version in `react-localization` or are you doing that?

**Comment by stefalda** [comment]
I’ve already done that.

**Pull request merged**
